# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['pdf_manager.py'],
    pathex=['d:\\scripts\\pdf_manager_gui'],
    binaries=[],
    datas=[('simple_pdf_manager.ico', '.')],
    hiddenimports=['PIL', 'fitz', 'PIL.Image', 'PIL.ImageOps'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'pytest', 'numpy', 'scipy', 'pandas', 'matplotlib',
        'cryptography', 'pydantic', 'pydantic_core', 'pydantic_settings',
        'pyasn1', 'pyasn1_modules', 'rsa', 'cachetools',
        'chromadb', 'langchain', 'langchain_core', 'langchain_community',
        'langsmith', 'langgraph_sdk', 'langchain_ollama', 'langchain_protocol',
        'langchain_text_splitters', 'onnxruntime', 'pypdfium2', 'pypdfium2_raw',
        'pdfminer', 'pdfplumber', 'reportlab',
        'requests', 'urllib3', 'certifi', 'idna', 'charset_normalizer',
        'aiohttp', 'multidict', 'yarl', 'frozenlist', 'aiosignal',
        'huggingface_hub', 'tokenizers', 'safetensors',
        'fastapi', 'starlette', 'uvicorn', 'httpx', 'httpcore',
        'h11', 'sniffio', 'anyio', 'click',
        'sqlalchemy', 'openpyxl', 'xlrd', 'xlwt',
        'seaborn', 'plotly',
        'sklearn', 'scikit-learn',
        'tensorflow', 'torch', 'torchvision',
        'jupyter', 'IPython', 'notebook',
        'selenium', 'bs4', 'lxml',
        'pygments', 'markdown', 'markdown_it', 'mdurl',
        'grpc', 'protobuf', 'google', 'google.protobuf',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='simple PDF Manager',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='simple_pdf_manager.ico',
)